name: 'meterdata'
version: '1.0.0'
config-version: 2

profile: 'meterdata'

log-path: "/tmp/dbt_logs"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by 'dbt clean'
  - "target"
  - "dbt_packages"

models:
  meterdata:
    # Config for all models in this project
    silver:
      +materialized: table
      +schema: silver
    gold:
      +materialized: table
      +schema: gold
